//! RAM-aware memory tuning model and generated configuration content.

use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryTier {
    Low,
    Mid,
    High,
}

impl MemoryTier {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Mid => "mid",
            Self::High => "high",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct MemoryTuning {
    pub tier: MemoryTier,
    pub swappiness: i64,
    pub watermark_scale: i64,
    pub dirty_bytes: i64,
    pub dirty_background: i64,
    pub zram_frac: f64,
    pub zram_cap_mb: i64,
}

pub fn tier_for_mem_kb(mem_kb: i64) -> MemoryTier {
    let gb = mem_kb as f64 / (1024.0 * 1024.0);
    if gb <= 16.0 {
        MemoryTier::Low
    } else if gb < 24.0 {
        MemoryTier::Mid
    } else {
        MemoryTier::High
    }
}

pub fn values_for(tier: MemoryTier) -> MemoryTuning {
    match tier {
        MemoryTier::Low => MemoryTuning {
            tier,
            swappiness: 60,
            watermark_scale: 100,
            dirty_bytes: 67_108_864,
            dirty_background: 16_777_216,
            zram_frac: 0.5,
            zram_cap_mb: 8192,
        },
        MemoryTier::Mid => MemoryTuning {
            tier,
            swappiness: 120,
            watermark_scale: 110,
            dirty_bytes: 134_217_728,
            dirty_background: 33_554_432,
            zram_frac: 1.0,
            zram_cap_mb: 8192,
        },
        MemoryTier::High => MemoryTuning {
            tier,
            swappiness: 180,
            watermark_scale: 125,
            dirty_bytes: 268_435_456,
            dirty_background: 67_108_864,
            zram_frac: 1.0,
            zram_cap_mb: 0,
        },
    }
}

fn read_memtotal_kb() -> i64 {
    let Ok(raw) = std::fs::read_to_string("/proc/meminfo") else {
        return 32 * 1024 * 1024;
    };
    raw.lines()
        .find(|line| line.starts_with("MemTotal:"))
        .and_then(|line| line.split_whitespace().nth(1))
        .and_then(|value| value.parse().ok())
        .unwrap_or(32 * 1024 * 1024)
}

pub fn config_path(path: Option<impl AsRef<Path>>) -> PathBuf {
    if let Some(path) = path {
        return path.as_ref().to_path_buf();
    }
    if std::env::var("KYTH_TEST_MODE").ok().as_deref() == Some("1") {
        if let Some(config) = std::env::var_os("XDG_CONFIG_HOME") {
            return PathBuf::from(config).join("kyth/memory-tune.toml");
        }
    }
    PathBuf::from("/etc/kyth/memory-tune.toml")
}

pub fn load(path: impl AsRef<Path>, mem_kb: Option<i64>) -> MemoryTuning {
    let fallback = || values_for(tier_for_mem_kb(mem_kb.unwrap_or_else(read_memtotal_kb)));
    let Ok(raw) = std::fs::read_to_string(path) else {
        return fallback();
    };
    let Ok(value) = raw.parse::<toml::Value>() else {
        return fallback();
    };
    let tier = match value
        .get("tier")
        .and_then(toml::Value::as_str)
        .unwrap_or("auto")
    {
        "low" => MemoryTier::Low,
        "mid" => MemoryTier::Mid,
        "high" => MemoryTier::High,
        _ => tier_for_mem_kb(mem_kb.unwrap_or_else(read_memtotal_kb)),
    };
    values_for(tier)
}

pub fn sysctl_content(config: &MemoryTuning) -> String {
    format!("# Kyth memory tune — {} (MemTotal scaling)\nvm.swappiness = {}\nvm.watermark_scale_factor = {}\nvm.dirty_bytes = {}\nvm.dirty_background_bytes = {}\n", config.tier.as_str(), config.swappiness, config.watermark_scale, config.dirty_bytes, config.dirty_background)
}

pub fn zram_content(config: &MemoryTuning) -> String {
    let size = if config.zram_cap_mb > 0 {
        format!("min(ram * {}, {})", config.zram_frac, config.zram_cap_mb)
    } else if config.zram_frac == 1.0 {
        "ram".into()
    } else {
        format!("ram * {}", config.zram_frac)
    };
    format!("[zram0]\nzram-size = {size}\ncompression-algorithm = zstd\nswap-priority = 100\n")
}

pub fn runtime_env_content(config: &MemoryTuning) -> String {
    format!("# Generated by kyth_shared.memory_tune — do not edit by hand\nKYTH_ZRAM_PERCENT={}\nKYTH_ZRAM_CAP_MB={}\nKYTH_ZRAM_ALGO=zstd\n", (config.zram_frac * 100.0).round() as i64, config.zram_cap_mb)
}

pub fn generate(config: &MemoryTuning, destination: impl AsRef<Path>) -> std::io::Result<PathBuf> {
    let destination = destination.as_ref();
    crate::atomic_io::atomic_write_text(destination, &sysctl_content(config), Some(0o644))?;
    Ok(destination.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn selects_documented_ram_tiers() {
        assert_eq!(tier_for_mem_kb(8 * 1024 * 1024), MemoryTier::Low);
        assert_eq!(tier_for_mem_kb(20 * 1024 * 1024), MemoryTier::Mid);
        assert_eq!(tier_for_mem_kb(32 * 1024 * 1024), MemoryTier::High);
    }

    #[test]
    fn loads_explicit_tier_and_generates_matching_content() {
        let directory = tempdir().unwrap();
        let config_path = directory.path().join("memory-tune.toml");
        let output = directory.path().join("memory.conf");
        std::fs::write(&config_path, "tier = \"low\"\n").unwrap();
        let config = load(&config_path, Some(32 * 1024 * 1024));
        assert_eq!(config.tier, MemoryTier::Low);
        generate(&config, &output).unwrap();
        assert!(std::fs::read_to_string(output)
            .unwrap()
            .contains("vm.swappiness = 60"));
        assert!(zram_content(&config).contains("min(ram * 0.5, 8192)"));
    }

    #[test]
    fn invalid_tier_uses_memory_size() {
        let directory = tempdir().unwrap();
        let path = directory.path().join("memory-tune.toml");
        std::fs::write(&path, "tier = \"unknown\"\n").unwrap();
        assert_eq!(load(&path, Some(20 * 1024 * 1024)).tier, MemoryTier::Mid);
    }
}
