//! Deterministic sysctl tier loading and rendering.
//!
//! This is the pure/read-and-render portion of
//! `kyth_shared.sysctl_compose`.  The build-time Python entry point remains
//! responsible for CLI exit policy and image orchestration, while Rust
//! callers can consume the same TOML contract without importing Python.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

pub const TIERS: [&str; 3] = ["base", "gaming", "network"];
pub const HEADER: &str = "# Generated by kyth_shared.sysctl_compose — do not edit directly. Source: build_files/config/sysctl/*.toml\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SysctlEntry {
    pub value: String,
    pub comment: String,
}

pub type Tier = BTreeMap<String, SysctlEntry>;
pub type Inputs = BTreeMap<String, Tier>;

fn scalar_text(value: &toml::Value) -> String {
    match value {
        toml::Value::String(value) => value.clone(),
        toml::Value::Integer(value) => value.to_string(),
        toml::Value::Float(value) => value.to_string(),
        toml::Value::Boolean(value) => value.to_string(),
        toml::Value::Datetime(value) => value.to_string(),
        toml::Value::Array(_) | toml::Value::Table(_) => value.to_string(),
    }
}

fn load_tier_file(tier: &str, config_dir: &Path) -> Tier {
    let path = config_dir.join(format!("{tier}.toml"));
    let Ok(raw) = std::fs::read_to_string(path) else {
        return BTreeMap::new();
    };
    let Ok(value) = raw.parse::<toml::Value>() else {
        return BTreeMap::new();
    };
    let Some(keys) = value.get("keys").and_then(toml::Value::as_table) else {
        return BTreeMap::new();
    };
    keys.iter()
        .filter_map(|(key, value)| {
            let table = value.as_table()?;
            let value = table
                .get("value")
                .map(scalar_text)
                .unwrap_or_default()
                .trim()
                .to_string();
            if value.is_empty() {
                return None;
            }
            let comment = table
                .get("comment")
                .map(scalar_text)
                .unwrap_or_default()
                .trim()
                .to_string();
            Some((key.trim().to_string(), SysctlEntry { value, comment }))
        })
        .collect()
}

/// Load the three canonical sysctl tiers. Missing or malformed tier files
/// behave like the Python composer: they contribute no keys.
pub fn load_inputs(config_dir: impl AsRef<Path>) -> Inputs {
    TIERS
        .iter()
        .map(|tier| {
            (
                (*tier).to_string(),
                load_tier_file(tier, config_dir.as_ref()),
            )
        })
        .collect()
}

/// Return duplicate-key descriptions in tier order.
pub fn duplicate_keys(inputs: &Inputs) -> Vec<String> {
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    let mut duplicates = Vec::new();
    for tier in TIERS {
        let Some(keys) = inputs.get(tier) else {
            continue;
        };
        // TOML tables are ordered by key in this implementation. Sorting here
        // also makes diagnostics deterministic for caller-supplied maps.
        for key in keys.keys() {
            if let Some(previous) = seen.get(key) {
                duplicates.push(format!(
                    "duplicate key {key:?} in tiers {previous:?} and {tier:?}"
                ));
            } else {
                seen.insert(key.clone(), tier.to_string());
            }
        }
    }
    duplicates
}

/// Render one tier with the same ordering and comments as the Python tool.
pub fn render_tier(keys: &Tier) -> String {
    if keys.is_empty() {
        return HEADER.to_string();
    }
    let mut output = String::from(HEADER);
    output.push('\n');
    for (key, entry) in keys {
        output.push_str(key);
        output.push_str(" = ");
        output.push_str(&entry.value);
        if !entry.comment.is_empty() {
            output.push_str("  # ");
            output.push_str(&entry.comment);
        }
        output.push('\n');
    }
    // Python's `_render_tier` joins a header that already ends in `\n` and
    // then appends another newline before the first key. Preserve that
    // generated-file contract.
    output.push('\n');
    output
}

/// Load and render all three tiers after checking for cross-tier duplicates.
pub fn compose(config_dir: impl AsRef<Path>) -> Result<BTreeMap<String, String>, Vec<String>> {
    let inputs = load_inputs(config_dir);
    let duplicates = duplicate_keys(&inputs);
    if !duplicates.is_empty() {
        return Err(duplicates);
    }
    Ok(TIERS
        .iter()
        .map(|tier| {
            (
                (*tier).to_string(),
                render_tier(inputs.get(*tier).unwrap_or(&BTreeMap::new())),
            )
        })
        .collect())
}

/// Write only the three generated tier files below an explicit destination.
/// This intentionally does not remove legacy files or apply sysctl values;
/// those side effects stay with the existing build/service owner.
pub fn write_tiers(
    config_dir: impl AsRef<Path>,
    destination: impl AsRef<Path>,
) -> std::io::Result<Vec<PathBuf>> {
    let rendered = compose(config_dir).map_err(|duplicates| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, duplicates.join("\n"))
    })?;
    let destination = destination.as_ref();
    std::fs::create_dir_all(destination)?;
    let mut written = Vec::new();
    for tier in TIERS {
        let path = destination.join(format!("99-kyth-{tier}.conf"));
        // The empty gaming tier is intentionally omitted to avoid activating
        // a stale header-only drop-in, matching the Python composer.
        if tier == "gaming" && rendered.get(tier).is_some_and(|text| text == HEADER) {
            match std::fs::remove_file(&path) {
                Ok(()) => {}
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(e),
            }
            continue;
        }
        crate::atomic_io::atomic_write_text(
            &path,
            rendered.get(tier).unwrap_or(&String::new()),
            Some(0o644),
        )?;
        written.push(path);
    }
    Ok(written)
}

/// Return all keys that are present in at least one tier.
pub fn key_set(inputs: &Inputs) -> BTreeSet<String> {
    inputs
        .values()
        .flat_map(|tier| tier.keys().cloned())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn loads_and_renders_real_tiers_without_duplicates() {
        let inputs = load_inputs("../../build_files/config/sysctl");
        assert!(duplicate_keys(&inputs).is_empty());
        let rendered = compose("../../build_files/config/sysctl").unwrap();
        assert!(rendered["base"].contains("vm.max_map_count = 16777216"));
        assert!(rendered["gaming"].contains("kernel.sched_bore = 1"));
        assert!(rendered["network"].contains("net.ipv4.tcp_congestion_control = bbr"));
        assert!(key_set(&inputs).len() > 30);
    }

    #[test]
    fn reports_duplicate_keys_in_tier_order() {
        let inputs = BTreeMap::from([
            (
                "base".into(),
                BTreeMap::from([(
                    "vm.swappiness".into(),
                    SysctlEntry {
                        value: "1".into(),
                        comment: String::new(),
                    },
                )]),
            ),
            ("gaming".into(), BTreeMap::new()),
            (
                "network".into(),
                BTreeMap::from([(
                    "vm.swappiness".into(),
                    SysctlEntry {
                        value: "2".into(),
                        comment: String::new(),
                    },
                )]),
            ),
        ]);
        let duplicates = duplicate_keys(&inputs);
        assert_eq!(
            duplicates,
            vec!["duplicate key \"vm.swappiness\" in tiers \"base\" and \"network\""]
        );
        assert!(compose_with_inputs_for_test(inputs).is_err());
    }

    fn compose_with_inputs_for_test(
        inputs: Inputs,
    ) -> Result<BTreeMap<String, String>, Vec<String>> {
        let duplicates = duplicate_keys(&inputs);
        if !duplicates.is_empty() {
            return Err(duplicates);
        }
        Ok(TIERS
            .iter()
            .map(|tier| {
                (
                    (*tier).into(),
                    render_tier(inputs.get(*tier).unwrap_or(&BTreeMap::new())),
                )
            })
            .collect())
    }

    #[test]
    fn writes_tiers_and_removes_empty_gaming_dropin() {
        let config = tempdir().unwrap();
        fs::write(
            config.path().join("base.toml"),
            "[keys.\"vm.swappiness\"]\nvalue = \"10\"\n",
        )
        .unwrap();
        fs::write(
            config.path().join("network.toml"),
            "[keys.\"net.ipv4.tcp_ecn\"]\nvalue = \"1\"\n",
        )
        .unwrap();
        let destination = tempdir().unwrap();
        fs::write(destination.path().join("99-kyth-gaming.conf"), "stale\n").unwrap();
        let written = write_tiers(config.path(), destination.path()).unwrap();
        assert_eq!(written.len(), 2);
        assert!(!destination.path().join("99-kyth-gaming.conf").exists());
        assert!(
            fs::read_to_string(destination.path().join("99-kyth-base.conf"))
                .unwrap()
                .contains("vm.swappiness = 10")
        );
    }
}
