//! Native owner of hardware-policy evaluation and application.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io;
use std::path::Path;
use std::process::ExitCode;
use std::time::Duration;

use kyth_shared::atomic_io::{atomic_write_json, atomic_write_text};
use kyth_shared::system::akmods_lock::{acquire, DEFAULT_LOCK_PATH, DEFAULT_TIMEOUT};
use kyth_shared::system::hardware_policy::{self, Evaluation, DEFAULT_POLICY_PATH};
use kyth_shared::system::process::run_bounded;

const STATE_PATH: &str = "/var/lib/kyth/hardware-policy.json";
const REPORT_PATH: &str = "/var/lib/kyth/hardware-support.json";
const MODPROBE_PATH: &str = "/etc/modprobe.d/90-kyth-hardware-policy.conf";
const SCX_PATH: &str = "/etc/scx/scx_loader.conf";

fn run(argv: &[String], timeout: Duration) -> io::Result<std::process::Output> {
    run_bounded(argv, timeout)
}

fn command_ok(argv: &[String], timeout: Duration) -> bool {
    run(argv, timeout).is_ok_and(|output| output.status.success())
}

fn host_command_exists(name: &str) -> bool {
    env::var_os("PATH")
        .is_some_and(|path| env::split_paths(&path).any(|directory| directory.join(name).is_file()))
}

fn evaluation(path: &Path) -> Result<Evaluation, String> {
    let (policy, digest) = hardware_policy::load_policy(path)?;
    Ok(hardware_policy::evaluate(
        &policy,
        &digest,
        hardware_policy::collect_inventory(),
    ))
}

fn safe_token(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 256
        && value.bytes().all(|byte| {
            byte.is_ascii_alphanumeric()
                || matches!(byte, b'_' | b'-' | b'.' | b',' | b':' | b'/' | b'+')
        })
}

fn render_modprobe(evaluation: &Evaluation) -> Result<String, String> {
    let mut lines = vec![
        "# Generated by kyth-hardware-policy. Do not edit.".to_string(),
        format!("# Policy revision: {}", evaluation.policy_revision),
    ];
    for quirk in &evaluation.quirks {
        let id = quirk
            .get("id")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("unknown");
        let reason = quirk
            .get("reason")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("");
        let expiry = quirk
            .get("expires_on")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("");
        lines.push(format!("# {id}: {reason} (review by {expiry})"));
        for action in quirk
            .get("actions")
            .and_then(serde_json::Value::as_array)
            .into_iter()
            .flatten()
        {
            let module = action
                .get("module")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("");
            if action.get("kind").and_then(serde_json::Value::as_str) != Some("modprobe")
                || !safe_token(module)
            {
                return Err(format!("unsafe hardware action for {id}"));
            }
            let options = action
                .get("options")
                .and_then(serde_json::Value::as_object)
                .ok_or_else(|| format!("missing options for {id}"))?;
            let mut rendered = BTreeMap::new();
            for (key, value) in options {
                let value = value
                    .as_str()
                    .ok_or_else(|| format!("non-string option for {id}"))?;
                if !safe_token(key) || !safe_token(value) {
                    return Err(format!("unsafe modprobe option for {id}"));
                }
                rendered.insert(key, value);
            }
            let options = rendered
                .into_iter()
                .map(|(key, value)| format!("{key}={value}"))
                .collect::<Vec<_>>()
                .join(" ");
            lines.push(format!("options {module} {options}"));
        }
    }
    Ok(format!("{}\n", lines.join("\n")))
}

fn profile_policy(evaluation: &Evaluation) -> (Vec<String>, bool) {
    let mut schedulers = Vec::new();
    let mut nvidia = false;
    for profile in &evaluation.profiles {
        if let Some(policy) = profile.get("policy") {
            if let Some(values) = policy
                .get("scheduler_candidates")
                .and_then(serde_json::Value::as_array)
            {
                for value in values.iter().filter_map(serde_json::Value::as_str) {
                    if !schedulers.iter().any(|candidate| candidate == value) {
                        schedulers.push(value.to_string());
                    }
                }
            }
            nvidia |= policy
                .get("nvidia_setup")
                .and_then(serde_json::Value::as_bool)
                .unwrap_or(false);
        }
    }
    (schedulers, nvidia)
}

fn configure_scheduler(candidates: &[String]) -> io::Result<String> {
    let disable = || {
        let _ = fs::remove_file(SCX_PATH);
        let _ = run(
            &[
                "systemctl".into(),
                "disable".into(),
                "--now".into(),
                "scx_loader.service".into(),
            ],
            Duration::from_secs(30),
        );
    };
    if !Path::new("/sys/kernel/sched_ext").is_dir() || !host_command_exists("scx_loader") {
        disable();
        return Ok("kernel-default".into());
    }
    let selected = candidates
        .iter()
        .find(|candidate| host_command_exists(candidate))
        .cloned();
    let Some(selected) = selected else {
        disable();
        return Ok("kernel-default".into());
    };
    atomic_write_text(
        SCX_PATH,
        &format!("SCX_SCHEDULER={selected}\n"),
        Some(0o600),
    )?;
    let _ = run(
        &[
            "systemctl".into(),
            "enable".into(),
            "scx_loader.service".into(),
        ],
        Duration::from_secs(30),
    );
    let _ = run(
        &[
            "systemctl".into(),
            "restart".into(),
            "scx_loader.service".into(),
        ],
        Duration::from_secs(30),
    );
    Ok(selected)
}

fn configure_nvidia() -> Result<String, String> {
    if !command_ok(
        &["rpm".into(), "-q".into(), "akmod-nvidia".into()],
        Duration::from_secs(30),
    ) {
        return Err("NVIDIA GPU matched, but akmod-nvidia is missing from the image".into());
    }
    let kernel = fs::read_to_string("/proc/sys/kernel/osrelease")
        .unwrap_or_default()
        .trim()
        .to_string();
    if !command_ok(
        &["modinfo".into(), "nvidia".into()],
        Duration::from_secs(30),
    ) {
        if kernel.is_empty() {
            return Err("unable to determine running kernel".into());
        }
        let lock =
            acquire(DEFAULT_LOCK_PATH, DEFAULT_TIMEOUT).map_err(|error| error.to_string())?;
        if !command_ok(
            &["modinfo".into(), "nvidia".into()],
            Duration::from_secs(30),
        ) {
            let output = run(
                &[
                    "akmods".into(),
                    "--force".into(),
                    "--kernels".into(),
                    kernel,
                ],
                DEFAULT_TIMEOUT,
            )
            .map_err(|error| error.to_string())?;
            if !output.status.success() {
                return Err("NVIDIA module build failed".into());
            }
        }
        drop(lock);
    }
    let args = "rd.driver.blacklist=nouveau,nova_core modprobe.blacklist=nouveau,nova_core nvidia-drm.modeset=1 nvidia-drm.fbdev=1";
    let _ = run(
        &[
            "grubby".into(),
            "--update-kernel=ALL".into(),
            format!("--args={args}"),
        ],
        Duration::from_secs(30),
    );
    for unit in [
        "nvidia-suspend.service",
        "nvidia-resume.service",
        "nvidia-hibernate.service",
    ] {
        let _ = run(
            &["systemctl".into(), "enable".into(), unit.into()],
            Duration::from_secs(30),
        );
    }
    Ok("proprietary-ready".into())
}

fn clear_nvidia() -> String {
    let args = "rd.driver.blacklist=nouveau,nova_core modprobe.blacklist=nouveau,nova_core nvidia-drm.modeset=1 nvidia-drm.fbdev=1";
    let _ = run(
        &[
            "grubby".into(),
            "--update-kernel=ALL".into(),
            format!("--remove-args={args}"),
        ],
        Duration::from_secs(30),
    );
    for unit in [
        "nvidia-suspend.service",
        "nvidia-resume.service",
        "nvidia-hibernate.service",
    ] {
        let _ = run(
            &["systemctl".into(), "disable".into(), unit.into()],
            Duration::from_secs(30),
        );
    }
    "not-required".into()
}

fn apply(
    policy_path: &Path,
    state_path: &Path,
    report_path: &Path,
    force: bool,
) -> Result<serde_json::Value, String> {
    if unsafe { libc::geteuid() } != 0 {
        return Err("hardware policy application must run as root".into());
    }
    let evaluation = evaluation(policy_path)?;
    let expected = render_modprobe(&evaluation)?;
    let kernel = fs::read_to_string("/proc/sys/kernel/osrelease")
        .unwrap_or_else(|_| "unknown".into())
        .trim()
        .to_string();
    let previous = fs::read_to_string(state_path)
        .ok()
        .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
        .unwrap_or_else(|| serde_json::json!({}));
    let identity = serde_json::json!({
        "policy_digest": evaluation.policy_digest,
        "inventory_digest": evaluation.inventory.digest(),
        "kernel": kernel,
    });
    let unchanged = !force
        && previous.get("status").and_then(serde_json::Value::as_str) == Some("applied")
        && identity.as_object().is_some_and(|values| {
            values
                .iter()
                .all(|(key, value)| previous.get(key) == Some(value))
        })
        && fs::read_to_string(MODPROBE_PATH).is_ok_and(|text| text.trim() == expected.trim());
    if unchanged {
        atomic_write_json(
            report_path,
            &serde_json::json!({"evaluation": evaluation, "applied": previous}),
            Some(0o600),
        )
        .map_err(|error| error.to_string())?;
        return Ok(previous);
    }
    atomic_write_text(MODPROBE_PATH, &expected, Some(0o644)).map_err(|error| error.to_string())?;
    let (schedulers, nvidia_setup) = profile_policy(&evaluation);
    let mut state = serde_json::json!({
        "schema_version": 1, "status": "applying", "policy_revision": evaluation.policy_revision,
        "profiles": evaluation.profiles.iter().filter_map(|profile| profile.get("id").and_then(serde_json::Value::as_str)).collect::<Vec<_>>(),
        "quirks": evaluation.quirks.iter().filter_map(|quirk| quirk.get("id").and_then(serde_json::Value::as_str)).collect::<Vec<_>>(),
        "capabilities": evaluation.capabilities, "recommended_variant": evaluation.recommended_variant,
        "warnings": evaluation.warnings, "error": "",
    });
    if let Some(object) = state.as_object_mut() {
        object.extend(identity.as_object().cloned().unwrap_or_default());
    }
    let result = (|| {
        let scheduler = configure_scheduler(&schedulers).map_err(|error| error.to_string())?;
        let nvidia = if nvidia_setup {
            configure_nvidia()?
        } else {
            clear_nvidia()
        };
        state["scheduler"] = scheduler.into();
        state["nvidia"] = nvidia.into();
        state["status"] = "applied".into();
        Ok::<(), String>(())
    })();
    if let Err(error) = result {
        state["status"] = "failed".into();
        state["error"] = error.clone().into();
        atomic_write_json(state_path, &state, Some(0o600)).map_err(|write| write.to_string())?;
        atomic_write_json(
            report_path,
            &serde_json::json!({"evaluation": evaluation, "applied": state}),
            Some(0o600),
        )
        .map_err(|write| write.to_string())?;
        return Err(error);
    }
    atomic_write_json(state_path, &state, Some(0o600)).map_err(|error| error.to_string())?;
    atomic_write_json(
        report_path,
        &serde_json::json!({"evaluation": evaluation, "applied": state}),
        Some(0o600),
    )
    .map_err(|error| error.to_string())?;
    Ok(state)
}

fn support_matrix(policy: &hardware_policy::Policy) -> String {
    let mut output = String::from(
        "# Hardware Support Matrix\n\n> Generated from `build_files/config/hardware-profiles.toml`; do not edit manually.\n\n## Image variants\n\n| Variant | Status | Intended hardware | Qualification |\n|---|---|---|---|\n",
    );
    for variant in &policy.variants {
        output.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            variant.id, variant.status, variant.description, variant.qualification
        ));
    }
    output.push_str("\n## Device profiles\n\n| Profile | Tier | Recommended variant | Capabilities |\n|---|---|---|---|\n");
    let mut profiles = policy.profiles.iter().collect::<Vec<_>>();
    profiles.sort_by_key(|profile| (-profile.priority, profile.id.clone()));
    for profile in profiles {
        let capabilities = if profile.capabilities.is_empty() {
            "—".to_string()
        } else {
            profile
                .capabilities
                .iter()
                .map(|value| format!("`{}`", value))
                .collect::<Vec<_>>()
                .join(", ")
        };
        output.push_str(&format!(
            "| `{}` | {} | `{}` | {} |\n",
            profile.id, profile.tier, profile.image_variant, capabilities
        ));
    }
    output.push_str(
        "\n## Managed quirks\n\n| Quirk | Review by | Reason | Provenance |\n|---|---|---|---|\n",
    );
    let mut quirks = policy.quirks.iter().collect::<Vec<_>>();
    quirks.sort_by_key(|quirk| quirk.id.clone());
    for quirk in quirks {
        output.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            quirk.id, quirk.expires_on, quirk.reason, quirk.provenance
        ));
    }
    output
}

fn usage() {
    eprintln!("usage: kyth-hardware-policy [--policy PATH] [--state PATH] <inventory|evaluate|apply [--force]|status|matrix [--output PATH]|validate [--fail-expired]>");
}

fn take_option(args: &mut Vec<String>, name: &str) -> Option<String> {
    let index = args.iter().position(|arg| arg == name)?;
    args.remove(index);
    (index < args.len()).then(|| args.remove(index))
}

fn main() -> ExitCode {
    let mut args = env::args().skip(1).collect::<Vec<_>>();
    let policy = take_option(&mut args, "--policy").unwrap_or_else(|| DEFAULT_POLICY_PATH.into());
    let state = take_option(&mut args, "--state").unwrap_or_else(|| STATE_PATH.into());
    let command = args.first().cloned().unwrap_or_default();
    let result: Result<(), String> = match command.as_str() {
        "inventory" => serde_json::to_string_pretty(&hardware_policy::collect_inventory())
            .map(|text| println!("{text}"))
            .map_err(|error| error.to_string()),
        "evaluate" => evaluation(Path::new(&policy))
            .map(|value| println!("{}", serde_json::to_string_pretty(&value).unwrap())),
        "status" => evaluation(Path::new(&policy)).map(|value| {
            let applied = fs::read_to_string(&state)
                .ok()
                .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
                .unwrap_or_else(|| serde_json::json!({}));
            println!(
                "{}",
                serde_json::to_string_pretty(
                    &serde_json::json!({"evaluation": value, "applied": applied})
                )
                .unwrap()
            );
        }),
        "apply" => apply(
            Path::new(&policy),
            Path::new(&state),
            Path::new(REPORT_PATH),
            args.iter().any(|arg| arg == "--force"),
        )
        .map(|value| println!("{}", serde_json::to_string_pretty(&value).unwrap())),
        "matrix" => hardware_policy::load_policy(Path::new(&policy)).and_then(|(policy, _)| {
            let rendered = support_matrix(&policy);
            if let Some(output) = take_option(&mut args, "--output") {
                atomic_write_text(output, &rendered, Some(0o644)).map_err(|error| error.to_string())
            } else {
                print!("{rendered}");
                Ok(())
            }
        }),
        "validate" => {
            hardware_policy::load_policy(Path::new(&policy)).and_then(|(policy, digest)| {
                println!(
                    "hardware policy {} ({}): valid",
                    policy.policy_revision,
                    &digest[..12]
                );
                let expired = hardware_policy::expired_quirks(&policy);
                if !expired.is_empty() {
                    eprintln!("expired quirks: {}", expired.join(", "));
                    if args.iter().any(|arg| arg == "--fail-expired") {
                        return Err("hardware policy contains expired quirks".into());
                    }
                }
                Ok(())
            })
        }
        _ => {
            usage();
            Ok(())
        }
    };
    if let Err(error) = result {
        eprintln!("kyth-hardware-policy: {error}");
        return ExitCode::from(1);
    }
    ExitCode::SUCCESS
}
